 repos:
   - repo: local
     hooks:
       - id: pylint
         name: pylint
         entry: pylint
         language: system
         types: [python]
         args:
           [
             "-rn",                                        # Only displays messages
             "-sn",                                        # Don't display scores
             "-rcfile=.pylintrc",                          # Link to your config file
             "--load-plugins=pylint.extensions.docparams"  # Load an extension
           ]